included: # paths to include during linting. `--path` is ignored if present.
  - DesktopOSX
  - DesktopOSXTests
  - DesktopOSXUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage